language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t maor30levy/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true maor30levy/docker-react npm run test
